### PR TITLE
Marbasoft/languages

### PR DESCRIPTION
**Pull request by MarbasFR**
In relation with my issue #272 
Not sure it's the best way. I notice than some strings was not found with the GenerateKeyLink as `Max Team 1 Players` or `Max Team 2 Players` in `Ruleset.cs`. They wasn't created in the xml (as all values in the LobbySettings).

I found them stored as this :` 000000005A91.07C: Max %1$s Players` in the DataTool's ouput

### CODE REVIEW

**Comment by ItsDeltin** [comment]
Amazing work! ❤️ The new translations and the 'Stop All Assists' fix has been added for the v2.0-beta.5 release.
enUS is 1:1 so the enUS translations shouldn't be loaded anyway.
I'm not sure if there are any side effects from upgrading dotnetcore 3.0 to 3.1 (but it's probably fine)

**Comment by MarbasFR** [comment]
Thanks for your comment :)

> enUS is 1:1 so the enUS translations shouldn't be loaded anyway.

in fact it's not 1:1. I've added `<method name="Both" alt="All" />`. `Both` does not exist, it's to have the difference between `PlayerSelector.all` and `Team.all`  :D

**Review by Protowalker — COMMENTED** [review]
What's the original purpose of `%1$s`?

**Comment by Protowalker** [comment]
All of these changes are ready to merge; @ItsDeltin besides the removal of what seems to be an important symbol `%1$s`

**Comment by MarbasFR** [comment]
> 
> 
> What's the original purpose of `%1$s`?
@Protowalker  : it's a replacement pattern. `Max %1$s Players ` can become `Max %Team 1 Players` or `Max Team 2 Players`

**Comment by Protowalker** [comment]
@ItsDeltin did we get all of these translations in?

**Pull request closed without merging**
