### PR TITLE
Fixed several typos preventing decompiling

### PR DESCRIPTION
**Pull request by Polymathical**
Case specific fix for issue #173

### CODE REVIEW

**Comment by TimeBomb** [comment]
Do you also need to update Enum.cs  and the various language files?
Were you able to get this to work correctly when using the compiled in VSCode? I was having issues after doing a replace-all in the entire project for these three typos. The decompiler kept giving me an out of range error.

**Comment by Polymathical** [comment]
Not sure about that problem. If you really want to mess with the code, open the solution in VS2019. I just ran a file to file decompile with an added a command line switch to take an inputfile and output file and kept fixing random things until the code would read end of file.

As far as replace all-- unless you use an engine that can differentiate symbols from just text, you're going to break a whole lot of things.

**Comment by ItsDeltin** [comment]
Thank you!

**Comment by TimeBomb** [comment]
@Polymathical To elaborate, I was specifically curious if we needed to update the language files, e.g.
https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/blob/master/Deltinteger/Deltinteger/Languages/i18n-frFR.xml#L397
And the Enums.cs file, https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/blob/master/Deltinteger/Deltinteger/Elements/Enums.cs#L240 https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/blob/master/Deltinteger/Deltinteger/Elements/Enums.cs#L280

On the latter point, I opened this project in VS 2019, replaced the files you replaced and the Enums.cs and the languages, compiled it, and tested the built release in VS Code, but ran into an error, so I wanted to confirm that this was working and decompiling appropriately.

**Comment by Polymathical** [comment]
Try sync'ing now that bossman has merged the pull request, and open another issue with out of bounds if it still happens?

**Pull request merged**
