### PR TITLE
Optimise all the things

### PR DESCRIPTION
**Pull request by TrueCP6**
- [x] `AbsoluteValue`
- [x] `Add`
- [x] `And`
- [x] `AngleBetweenVectors`
- [x] `AngleDifference`
- [x] `ArccosineInDegrees`
- [x] `ArccosineInRadians`
- [x] `ArcsineInDegrees`
- [x] `ArcsineInRadians`
- [x] `ArctangentInDegrees`
- [x] `ArctangentInRadians`
- [x] `Compare`
- [x] `CosineFromDegrees`
- [x] `CosineFromRadians`
- [x] `CrossProduct`
- [x] `DirectionFromAngles`
- [x] `DirectionTowards`
- [x] `DistanceBetween`
- [x] `Divide`
- [x] `DotProduct`
- [x] `HorizontalAngleFromDirection`
- [x] `Max`
- [x] `Min`
- [x] `Modulo`
- [x] `Multiply`
- [x] `Normalize`
- [x] `Not`
- [x] `Or`
- [x] `RaiseToPower`
- [x] `RoundToInteger`
- [x] `SineFromDegrees`
- [x] `SineFromRadians`
- [x] `SquareRoot`
- [x] `Subtract`
- [x] `TangentFromDegrees`
- [x] `TangentFromRadians`
- [x] `VectorTowards`
- [x] `VerticalAngleFromDirection`
- [x] `XOf`
- [x] `YOf`
- [x] `ZOf`

Thanks to @Zezombye for [a lot of the optimisations](https://github.com/Zezombye/overpy/issues/33).

To do:
- [x] Allow EqualsTo to work with Elements, Variables and Enums
- [x] Constant support for `Up`, `Down`, `Left`, `Right`, `Forward`, `Backward`

Stuff that could be done but would be a pain and wouldn't be that useful:
- `ArrayContains`
- `ArraySlice`
- `CountOf`
- `FilteredArray`
- `FirstOf`
- `IsTrueForAll`
- `IsTrueForAny`
- `LastOf`
- `IndexOfArrayValue`
- `RemoveFromArray`
- `SortedArray`
- `ValueInArray`

### CODE REVIEW

**Comment by Zezombye** [comment]
Careful though :
- Checking if things are equal must take into account the random() functions
- The boolean operators do short-circuiting, so true && 3 must return 3 and not true

**Comment by TrueCP6** [comment]
Does the short-circuiting only happen with number constants or can it happen with a variable or other elements?

**Comment by Zezombye** [comment]
Everything, like in JS.

**Comment by TrueCP6** [comment]
Ready for review

**Pull request merged**
