### PR TITLE
Add rotation parameter for wireframe methods

### LINKED ISSUE #56: Directional vector rotation parameter for wireframe methods
I had a go at this for #53 but was unsuccessful.

The math I used for each point which resulted in a distorted rotation looked like this:
`point1 + DistanceBetween(point1, point2) * (direction + DirectionTowards(point1, point2))` where point1 is Vector(0,0,0) and point2 is the position of the point.

### LINKED ISSUE #61: CreateInworldText missing the spectators parameter
Here is the code causing the problem in OSTW:
```
CreateInWorldText(FilteredArray(AllPlayers(), ArrayElement().arena == 6), <"waiting <0> next_round", 4>, barrierPositions[3], 2, Clipping.ClipAgainstSurfaces, InworldTextRev.VisibleToPositionAndString);
```
And here is the output code where the PTR detects the problem:
```
Create In-World Text(Filtered Array(All Players(Team(All)), Compare(Value In Array(Player Variable(Current Array Element, A), 0), ==, 6)), String("{0} {1} {2}", String("waiting", Null, Null, Null), 4, String("next round", Null, Null, Null)), Value In Array(Value In Array(Global Variable(A), 3), 3), 2, Clip Against Surfaces, Visible To Position And String);
```

### LINKED ISSUE #66: EyeCastHitPosition hits Event Player

### PR DESCRIPTION
**Pull request by TrueCP6**
- [x] Add parameters
- [x] Get rotation working
- [x] Add option for no rotation re-evaluation
- [x] Close #61
- [x] Fix Vertex.Rotate(Vertex xyz) crash
- [x] Solve non-existing rule problem (#65), (my bad)
- [x] Verify that non-reevaluating rotation works as intended
- [x] Find and implement a formula that works as intended

Will close #61, will close #56 and will close #66.

### CODE REVIEW

**Comment by ItsDeltin** [comment]
Great work! 4408c6f0b3bd60d4af2cea8533885d80340d566a removes the `Reevaluate Rotation` parameter and will instead check if the rotation vector parameter is a constant. I should do the same thing with the scale. `ShowWireframe` tested and works, text model methods are not tested yet.

**Comment by TrueCP6** [comment]
I gave it a try with `CreateTextMinimal` but it throws an exception.

This is the error log:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Deltin.Deltinteger.Models.Vertex.Rotate(Vertex xyz) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Models\Vertex.cs:line 60
   at Deltin.Deltinteger.Models.Import.StringModel..ctor(String text, FontFamily family, Double quality, Vertex angle, Double scale, Double angleRound) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Models\Import\String.cs:line 52
   at Deltin.Deltinteger.Models.Model.ImportString(String text, FontFamily family, Double quality, Vertex angle, Double scale, Double angleRound) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Models\Models.cs:line 41
   at Deltin.Deltinteger.Models.ModelCreator.RenderText(String text, String font, Double quality, Element visibleTo, Element location, Double scale, IWorkshopTree effectRev, Boolean getIds, Double angleRound, Element rotation) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Models\ModelMethods.cs:line 105
   at Deltin.Deltinteger.Models.CreateTextMinimal.Get() in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Models\ModelMethods.cs:line 328
   at Deltin.Deltinteger.Elements.CustomMethodBase.Result() in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Custom Methods\CustomMethods.cs:line 165
   at Deltin.Deltinteger.Parse.TranslateRule.ParseMethod(ScopeGroup scope, MethodNode methodNode, Boolean needsToBeValue) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 516
   at Deltin.Deltinteger.Parse.TranslateRule.ParseStatement(ScopeGroup scope, Node statement, IndexedVar returnVar) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 714
   at Deltin.Deltinteger.Parse.TranslateRule.ParseBlock(ScopeGroup scopeGroup, BlockNode blockNode, Boolean fulfillReturns, IndexedVar returnVar) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 702
   at Deltin.Deltinteger.Parse.TranslateRule..ctor(RuleNode ruleNode, ScopeGroup root, ParsingData parserData) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 43
   at Deltin.Deltinteger.Parse.TranslateRule.GetRule(RuleNode ruleNode, ScopeGroup root, ParsingData parserData) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\TranslateRule.cs:line 14
   at Deltin.Deltinteger.Parse.ParsingData..ctor(String file, String content) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Parse.cs:line 58
   at Deltin.Deltinteger.Parse.ParsingData.GetParser(String file, String content) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Parse\Parse.cs:line 18
   at Deltin.Deltinteger.LanguageServer.Server.ParseDocument(String input) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Language Server\Server.cs:line 149
   at Deltin.Deltinteger.LanguageServer.Server.RequestLoop(Int32 serverPort) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Language Server\Server.cs:line 60
   at Deltin.Deltinteger.Program.Main(String[] args) in C:\Users\minec\Google Drive\Games\Overwatch\OSTW\Overwatch-Script-To-Workshop\Deltinteger\Deltinteger\Program.cs:line 41
```

**Comment by TrueCP6** [comment]
Also it doesn't seem to work with `ShowWireframe` and a non-constant rotation. Only the variable guide is outputted:
```
// --- Variable Guide ---
// global A[0] INTERNAL : Multidimensional Array Builder
// player A[0] location
```

The OSTW code causing this is:
```
define playervar location;
import "D:\test\cone.obj" as cone;

rule:"test"
Event.OngoingPlayer
if (IsButtonHeld(EventPlayer(), Button.Interact))
{
    location = PositionOf(EventPlayer()) + Vector(0, 1, 0);
    ShowWireframe(cone, AllPlayers(), location, FacingDirectionOf(EventPlayer()), 1, EffectRev.VisibleToPositionAndRadius, false);
}
```

It doesn't seem that 8773a09 is causing this, The parser doesn't get to `CreateLine` so my guess is that it is a caught exception in an unknown location.

**Comment by TrueCP6** [comment]
Even without `ShowWireframe` whenever `import "file" as model` is present rules don't show up in the output code. Error highlighting doesn't work either when `import` is present. No idea to the cause of this.

**Comment by TrueCP6** [comment]
Turns out the formula I'm using doesn't work properly, will have to find another.

**Comment by ItsDeltin** [comment]
Before 8773a09 the Z rotation worked, Y deformed the object and X did nothing.

 [Heres](https://pastebin.com/BT73Qdqx) a script that can help debug, Crouching + moving left/right will rotate X, crouching + moving forward/backwards will rotate Y, crouching + primary/secondary fire will rotate Z.

**Comment by TrueCP6** [comment]
I reverted back to the method before that commit. Right now it works with horizontal rotation, but deforms as vertical axis changes. I've gotten it correctly rotating on the vertical axis only when facing almost straight up or down. Once I've found a method that works as intended I will try to optimize it by pre-calculating constant operations like `DistanceBetween`, etc.

**Comment by TrueCP6** [comment]
Should be ready for merge now, rotation now works as intended. May still need some testing.

**Comment by ItsDeltin** [comment]
I think the "script too large" error is when the file size of the script gets too big.

**Pull request merged**
