### PR TITLE
Fix: incorrect double format for workshop numbers.

### LINKED ISSUE #32: Wait (ContinueSkip) format number incorrect.
In for/foreach loop is `Wait(0,016, Ignore Condition); // ContinueSkip Wait` but need to be `0.016` because workshop paste will throw error because workshop try parse `0` and `016` as function param.

Another issue: `Wait(0.025)` in script, results as `Wait(25)` in output:
image

### PR DESCRIPTION
**Pull request by nathan130200**
Fix only double format incorrect in #32

Script:
```
rule: "Test"
{
	foreach(define player in AllPlayers())
		SmallMessage(player, <"Current objective: Survive">);
}
```

Output:
```
// --- Variable Guide ---
// global A[0] INTERNAL : ContinueSkip
// global A[1] INTERNAL : 'player' for index
// element reference : player

rule("Test")
{

	event
	{
		Ongoing - Global;
	}
	
	// Action count: 9
	actions
	{
		Wait(0,016, Ignore Condition); // ContinueSkip Wait
		Skip If(Compare(Value In Array(Global Variable(A), 0), !=, 0), Value In Array(Global Variable(A), 0)); // ContinueSkip Skipper
		Set Global Variable At Index(A, 1, 0);
		Skip If(Not(Compare(Value In Array(Global Variable(A), 1), <, Count Of(All Players(Team(All))))), 4);
		Small Message(Value In Array(All Players(Team(All)), Value In Array(Global Variable(A), 1)), String("{0} {1} {2}", String("current", Null, Null, Null), String("{0}:", String("objective", Null, Null, Null), Null, Null), String("survive", Null, Null, Null)));
		Set Global Variable At Index(A, 1, Add(Value In Array(Global Variable(A), 1), 1));
		Set Global Variable At Index(A, 0, 1);
		Loop;
		Set Global Variable At Index(A, 0, 0);
	}
}
```

correct format: `Wait(0.016, Ignore Condition);`

### CODE REVIEW

**Comment by nathan130200** [comment]
no response ???

**Comment by nathan130200** [comment]
double ToString() set different result to different value based on system language, provide an NumberFormatInfo with separators as dot `.` or CultureInfo.InvariantCulture.

**Comment by nathan130200** [comment]
Hello? I think you don't known how to use git repo, fck.

**Comment by TrueCP6** [comment]
Maybe re open and wait for response.

**Pull request closed without merging**
